In [1]:
import pandas as pd
import numpy as np

In [2]:
    #series from list 

#string 
country = ['India','pakistan','america','iran','indonesia']
pd.Series(country)

0        India
1     pakistan
2      america
3         iran
4    indonesia
dtype: str

In [3]:
# Integer

runs = [13,24,53,45,21]
pd.Series(runs,dtype='int16')

0    13
1    24
2    53
3    45
4    21
dtype: int16

In [4]:
#coustom index 

marks = [45,34,54,23]
subject = ["maths","science","English","hindi"]

pd.Series(marks,index=subject)

maths      45
science    34
English    54
hindi      23
dtype: int64

In [5]:
#setting name

marks = [45,34,54,23]
subject = ["maths","science","English","hindi"]

pd.Series(marks,index=subject,name="Vedanti ke marks")

maths      45
science    34
English    54
hindi      23
Name: Vedanti ke marks, dtype: int64

In [6]:
#series from dictionary 

marks = {'maths':89,
         'science':78,
         'hindi':56,
         'English':79}

marks_series = pd.Series(marks,name="Yash ke marks")
marks_series

maths      89
science    78
hindi      56
English    79
Name: Yash ke marks, dtype: int64

In [7]:
fruits = {"Apples":30,
         "bananas":21}

pd.Series(fruits)
print(fruits)

{'Apples': 30, 'bananas': 21}

In [8]:
import pandas as pd
print(pd.__version__)

3.0.1

In [9]:
#Series Attributes

#size 
marks_series.size

4

In [10]:
#dtype

marks_series.dtype

dtype('int64')

In [11]:
#name 

marks_series.name

'Yash ke marks'

In [12]:
#is unique imp

marks_series.is_unique

True

In [13]:
#index --> index object

marks_series.index

Index(['maths', 'science', 'hindi', 'English'], dtype='str')

In [14]:
runs.index

In [15]:
#values

marks_series.values

array([89, 78, 56, 79])

In [16]:
#Series using read_csv 

bmw = pd.read_csv('/Users/yashnandankar/StaTic_NeuraL/AI_Learn/bmw_global_sales_2018_2025.csv',index_col='Model')
bmw

,Year,Month,Region,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
Model,,,,,,,,,,
3 Series,2018,1,Europe,7822,47482,371404204,0.011,19.12,3.50,1.00
5 Series,2018,1,Europe,10280,61685,634121800,0.019,19.12,3.50,1.00
X3,2018,1,Europe,3105,58433,181434465,0.022,19.12,3.50,1.00
X5,2018,1,Europe,7420,67955,504226100,0.021,19.12,3.50,1.00
X7,2018,1,Europe,8474,92300,782150200,0.035,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...
X5,2025,12,RestOfWorld,9281,68198,632945638,0.201,5.89,2.37,1.41
X7,2025,12,RestOfWorld,12785,91839,1174161615,0.203,5.89,2.37,1.41
i4,2025,12,RestOfWorld,4906,63437,311221922,0.180,5.89,2.37,1.41
iX,2025,12,RestOfWorld,7871,73867,581407157,0.196,5.89,2.37,1.41
MINI,2025,12,RestOfWorld,6732,41811,281471652,0.167,5.89,2.37,1.41

In [17]:
bmw.head(10)

,Year,Month,Region,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
Model,,,,,,,,,,
3 Series,2018,1,Europe,7822,47482,371404204,0.011,19.12,3.50,1.00
5 Series,2018,1,Europe,10280,61685,634121800,0.019,19.12,3.50,1.00
X3,2018,1,Europe,3105,58433,181434465,0.022,19.12,3.50,1.00
X5,2018,1,Europe,7420,67955,504226100,0.021,19.12,3.50,1.00
X7,2018,1,Europe,8474,92300,782150200,0.035,19.12,3.50,1.00
i4,2018,1,Europe,10607,64082,679717774,0.035,19.12,3.50,1.00
iX,2018,1,Europe,4805,73975,355449875,0.016,19.12,3.50,1.00
MINI,2018,1,Europe,2554,43005,109834770,0.013,19.12,3.50,1.00
3 Series,2018,1,China,3826,48068,183908168,0.021,17.60,2.37,1.02
5 Series,2018,1,China,7498,62435,468137630,0.015,17.60,2.37,1.02

In [18]:
bmw.tail(3)

,Year,Month,Region,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
Model,,,,,,,,,,
i4,2025,12,RestOfWorld,4906,63437,311221922,0.180,5.89,2.37,1.41
iX,2025,12,RestOfWorld,7871,73867,581407157,0.196,5.89,2.37,1.41
MINI,2025,12,RestOfWorld,6732,41811,281471652,0.167,5.89,2.37,1.41

In [19]:
#Sample -> Extract one data random
bmw.sample(7)

,Year,Month,Region,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
Model,,,,,,,,,,
iX,2020,7,China,5643,73018,412040574,0.065,16.19,2.22,1.10
i4,2020,3,Europe,10897,65307,711650379,0.060,15.31,4.48,1.09
X7,2019,4,Europe,2843,93188,264933484,0.054,17.63,3.98,1.04
X7,2022,12,Europe,13906,90555,1259257830,0.117,14.24,1.31,1.22
iX,2018,6,Europe,7067,74633,527431411,0.023,17.17,1.67,0.98
X7,2020,5,RestOfWorld,10039,92838,932000682,0.084,5.44,3.01,1.07
5 Series,2019,9,Europe,3608,61851,223158408,0.043,14.35,3.91,1.09

In [20]:
#Values counts
bmw.value_counts()

Year  Month  Region       Units_Sold  Avg_Price_EUR  Revenue_EUR  BEV_Share  Premium_Share  GDP_Growth  Fuel_Price_Index
2018  1      Europe       7822        47482          371404204    0.011      19.12          3.50        1.00                1
                          10280       61685          634121800    0.019      19.12          3.50        1.00                1
                          3105        58433          181434465    0.022      19.12          3.50        1.00                1
                          7420        67955          504226100    0.021      19.12          3.50        1.00                1
                          8474        92300          782150200    0.035      19.12          3.50        1.00                1
                                                                                                                           ..
2025  12     RestOfWorld  9281        68198          632945638    0.201      5.89           2.37        1.41                1
                          12785       91839          1174161615   0.203      5.89           2.37        1.41                1
                          4906        63437          311221922    0.180      5.89           2.37        1.41                1
                          7871        73867          581407157    0.196      5.89           2.37        1.41                1
                          6732        41811          281471652    0.167      5.89           2.37        1.41                1
Name: count, Length: 3072, dtype: int64

In [21]:
bmw.index.value_counts()

Model
3 Series    384
5 Series    384
X3          384
X5          384
X7          384
i4          384
iX          384
MINI        384
Name: count, dtype: int64

In [22]:
code = pd.read_csv('/Users/yashnandankar/StaTic_NeuraL/AI_Learn/coding_hours_dataset.csv')
code

       Coding_Hours  Coffee_Cups  Bugs_Fixed
0                 7            3          35
1                 4            4          26
2                11            6          57
3                 8            7          48
4                 5            4          27
...             ...          ...         ...
24995             5            3          23
24996             1            1           6
24997             6            4          28
24998             3            3          17
24999             1            1          10

[25000 rows x 3 columns]

In [23]:
code.sort_values(by='Coding_Hours',ascending=True)

       Coding_Hours  Coffee_Cups  Bugs_Fixed
24999             1            1          10
18332             1            2           5
7852              1            1           2
7847              1            0           7
18337             1            1           3
...             ...          ...         ...
18412            12            5          57
16535            12            7          57
16534            12            8          63
20891            12            6          58
3514             12            6          59

[25000 rows x 3 columns]

In [24]:
code.sort_index(inplace=True)
code

       Coding_Hours  Coffee_Cups  Bugs_Fixed
0                 7            3          35
1                 4            4          26
2                11            6          57
3                 8            7          48
4                 5            4          27
...             ...          ...         ...
24995             5            3          23
24996             1            1           6
24997             6            4          28
24998             3            3          17
24999             1            1          10

[25000 rows x 3 columns]

In [25]:
#Series Math methods

#count

bmw.count()

Year                3072
Month               3072
Region              3072
Units_Sold          3072
Avg_Price_EUR       3072
Revenue_EUR         3072
BEV_Share           3072
Premium_Share       3072
GDP_Growth          3072
Fuel_Price_Index    3072
dtype: int64

In [26]:
code.sum()

Coding_Hours    161843
Coffee_Cups      93813
Bugs_Fixed      821782
dtype: int64

In [27]:
code.mean()

Coding_Hours     6.47372
Coffee_Cups      3.75252
Bugs_Fixed      32.87128
dtype: float64

In [28]:
code.median()

Coding_Hours     6.0
Coffee_Cups      4.0
Bugs_Fixed      33.0
dtype: float64

In [29]:
code.mode()

   Coding_Hours  Coffee_Cups  Bugs_Fixed
0            10            4          45

In [30]:
code.std()

Coding_Hours     3.450152
Coffee_Cups      1.992885
Bugs_Fixed      17.556006
dtype: float64

In [31]:
code.var()

Coding_Hours     11.903546
Coffee_Cups       3.971593
Bugs_Fixed      308.213360
dtype: float64

In [32]:
code.min()
print(code.max())

Coding_Hours    12
Coffee_Cups     10
Bugs_Fixed      73
dtype: int64

In [33]:
code.describe()

       Coding_Hours   Coffee_Cups    Bugs_Fixed
count  25000.000000  25000.000000  25000.000000
mean       6.473720      3.752520     32.871280
std        3.450152      1.992885     17.556006
min        1.000000      0.000000      0.000000
25%        3.000000      2.000000     18.000000
50%        6.000000      4.000000     33.000000
75%        9.000000      5.000000     48.000000
max       12.000000     10.000000     73.000000

In [34]:
bmw.describe()

,Year,Month,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
count,3072.000000,3072.000000,3072.000000,3072.000000,3.072000e+03,3072.000000,3072.000000,3072.000000,3072.000000
mean,2021.500000,6.500000,7980.288086,63854.561523,5.113995e+08,0.107572,14.660234,3.057526,1.176224
std,2.291661,3.452615,3174.917444,14655.891299,2.431185e+08,0.058099,5.334604,1.018103,0.118123
min,2018.000000,1.000000,2379.000000,40011.000000,1.045314e+08,-0.015000,5.090000,0.100000,0.920000
25%,2019.750000,3.750000,5225.500000,54500.250000,3.125504e+08,0.057000,12.275000,2.370000,1.080000
50%,2021.500000,6.500000,7985.500000,63493.000000,4.808690e+08,0.108000,16.260000,3.060000,1.180000
75%,2023.250000,9.250000,10528.250000,71489.500000,6.709141e+08,0.157250,18.932500,3.852500,1.270000
max,2025.000000,12.000000,15914.000000,93994.000000,1.433482e+09,0.223000,20.970000,5.820000,1.410000

In [35]:
#Series indexing 

#integer indexing  Works only on +ve indexing
x = pd.Series([12,23,12,43,45,61,23,34,12,4,2])
x[2]

np.int64(12)

In [36]:
marks_series

maths      89
science    78
hindi      56
English    79
Name: Yash ke marks, dtype: int64

In [37]:
#Editing Series

#using indexing 

marks_series['hindi'] = 46
print(marks_series)

maths      89
science    78
hindi      46
English    79
Name: Yash ke marks, dtype: int64

In [38]:
run = pd.read_csv('/Users/yashnandankar/StaTic_NeuraL/AI_Learn/kohli_ipl.csv')
run

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [39]:
run[[1]] = 2

print(run)

     match_no  runs  1
0           1     1  2
1           2    23  2
2           3    13  2
3           4    12  2
4           5     1  2
..        ...   ... ..
210       211     0  2
211       212    20  2
212       213    73  2
213       214    25  2
214       215     7  2

[215 rows x 3 columns]

In [50]:
#Series with python functionalities 

print(len(bmw))
print(type(bmw))
print(dir(bmw))
print(sorted(bmw))
print(min(bmw))
print(max(bmw))

3072
<class 'pandas.DataFrame'>
['Avg_Price_EUR', 'BEV_Share', 'Fuel_Price_Index', 'GDP_Growth', 'Month', 'Premium_Share', 'Region', 'Revenue_EUR', 'T', 'Units_Sold', 'Year', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__dataframe__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_arith_method_with_reindex', '_attrs', '_box_col_values', '_can_fast_transpose', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_combine_frame', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_from_mgr', '_constructor_sliced', '_constructor_sliced_from_mgr', '_dir_additions', '_dir_deletions', '_dispatch_frame_op', '_drop_axis', '_drop_labels_or_levels', '_ensure_valid_index', '_find_valid_index', '_flags', '_flex_arith_method', '_flex_cmp_method', '_from_arrays', '_from_mgr', '_get_agg_axis', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_column_array', '_get_index_resolvers', '_get_item', '_get_label_or_level_values', '_get_numeric_data', '_get_value', '_get_values_for_csv', '_getitem_bool_array', '_getitem_multilevel', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_info_repr', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_homogeneous_type', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_iset_item', '_iset_item_mgr', '_iset_not_inplace', '_iter_column_arrays', '_ixs', '_logical_func', '_logical_method', '_maybe_align_series_as_frame', '_metadata', '_mgr', '_min_count_stat_function', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_reduce_axis1', '_reindex_axes', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_columnwise', '_repr_data_resource_', '_repr_fits_horizontal_', '_repr_fits_vertical_', '_repr_html_', '_repr_latex_', '_reset_cache', '_sanitize_column', '_series', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_item', '_set_item_frame_value', '_set_item_mgr', '_set_value', '_setitem_array', '_setitem_frame', '_setitem_slice', '_shift_with_freq', '_should_reindex_frame_op', '_slice', '_stat_function', '_stat_function_ddof', '_to_dict_of_blocks', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'asfreq', 'asof', 'assign', 'astype', 'at', 'at_time', 'attrs', 'axes', 'between_time', 'bfill', 'boxplot', 'clip', 'columns', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'corrwith', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'eval', 'ewm', 'expanding', 'explode', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'from_dict', 'from_records', 'ge', 'get', 'groupby', 'gt', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'insert', 'interpolate', 'isetitem', 'isin', 'isna', 'isnull', 'items', 'iterrows', 'itertuples', 'join', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'melt', 'memory_usage', 'merge', 'min', 'mod', 'mode', 'mul', 'multiply', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'pivot', 'pivot_table', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'query', 'radd', 'rank', 'rdiv', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'select_dtypes', 'sem', 'set_axis', 'set_flags', 'set_index', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'stack', 'std', 'style', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_feather', 'to_hdf', 'to_html', 'to_iceberg', 'to_json', 'to_latex', 'to_markdown', 'to_numpy', 'to_orc', 'to_parquet', 'to_period', 'to_pickle', 'to_records', 'to_sql', 'to_stata', 'to_string', 'to_timestamp', 'to_xarray', 'to_xml', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
['Avg_Price_EUR', 'BEV_Share', 'Fuel_Price_Index', 'GDP_Growth', 'Month', 'Premium_Share', 'Region', 'Revenue_EUR', 'Units_Sold', 'Year']
Avg_Price_EUR
Year

In [51]:
#type conversion

list(bmw)

['Year',
 'Month',
 'Region',
 'Units_Sold',
 'Avg_Price_EUR',
 'Revenue_EUR',
 'BEV_Share',
 'Premium_Share',
 'GDP_Growth',
 'Fuel_Price_Index']

In [52]:
dict(bmw)

{'Year': Model
 3 Series    2018
 5 Series    2018
 X3          2018
 X5          2018
 X7          2018
             ...
 X5          2025
 X7          2025
 i4          2025
 iX          2025
 MINI        2025
 Name: Year, Length: 3072, dtype: int64,
 'Month': Model
 3 Series     1
 5 Series     1
 X3           1
 X5           1
 X7           1
             ..
 X5          12
 X7          12
 i4          12
 iX          12
 MINI        12
 Name: Month, Length: 3072, dtype: int64,
 'Region': Model
 3 Series         Europe
 5 Series         Europe
 X3               Europe
 X5               Europe
 X7               Europe
                ...
 X5          RestOfWorld
 X7          RestOfWorld
 i4          RestOfWorld
 iX          RestOfWorld
 MINI        RestOfWorld
 Name: Region, Length: 3072, dtype: str,
 'Units_Sold': Model
 3 Series     7822
 5 Series    10280
 X3           3105
 X5           7420
 X7           8474
             ...
 X5           9281
 X7          12785
 i4           4906
 iX           7871
 MINI         6732
 Name: Units_Sold, Length: 3072, dtype: int64,
 'Avg_Price_EUR': Model
 3 Series    47482
 5 Series    61685
 X3          58433
 X5          67955
 X7          92300
             ...
 X5          68198
 X7          91839
 i4          63437
 iX          73867
 MINI        41811
 Name: Avg_Price_EUR, Length: 3072, dtype: int64,
 'Revenue_EUR': Model
 3 Series     371404204
 5 Series     634121800
 X3           181434465
 X5           504226100
 X7           782150200
                ...
 X5           632945638
 X7          1174161615
 i4           311221922
 iX           581407157
 MINI         281471652
 Name: Revenue_EUR, Length: 3072, dtype: int64,
 'BEV_Share': Model
 3 Series    0.011
 5 Series    0.019
 X3          0.022
 X5          0.021
 X7          0.035
             ...
 X5          0.201
 X7          0.203
 i4          0.180
 iX          0.196
 MINI        0.167
 Name: BEV_Share, Length: 3072, dtype: float64,
 'Premium_Share': Model
 3 Series    19.12
 5 Series    19.12
 X3          19.12
 X5          19.12
 X7          19.12
             ...
 X5           5.89
 X7           5.89
 i4           5.89
 iX           5.89
 MINI         5.89
 Name: Premium_Share, Length: 3072, dtype: float64,
 'GDP_Growth': Model
 3 Series    3.50
 5 Series    3.50
 X3          3.50
 X5          3.50
 X7          3.50
             ...
 X5          2.37
 X7          2.37
 i4          2.37
 iX          2.37
 MINI        2.37
 Name: GDP_Growth, Length: 3072, dtype: float64,
 'Fuel_Price_Index': Model
 3 Series    1.00
 5 Series    1.00
 X3          1.00
 X5          1.00
 X7          1.00
             ...
 X5          1.41
 X7          1.41
 i4          1.41
 iX          1.41
 MINI        1.41
 Name: Fuel_Price_Index, Length: 3072, dtype: float64}

In [61]:
#Membership operator
"Region" in bmw

True

In [57]:
bmw

,Year,Month,Region,Units_Sold,Avg_Price_EUR,Revenue_EUR,BEV_Share,Premium_Share,GDP_Growth,Fuel_Price_Index
Model,,,,,,,,,,
3 Series,2018,1,Europe,7822,47482,371404204,0.011,19.12,3.50,1.00
5 Series,2018,1,Europe,10280,61685,634121800,0.019,19.12,3.50,1.00
X3,2018,1,Europe,3105,58433,181434465,0.022,19.12,3.50,1.00
X5,2018,1,Europe,7420,67955,504226100,0.021,19.12,3.50,1.00
X7,2018,1,Europe,8474,92300,782150200,0.035,19.12,3.50,1.00
...,...,...,...,...,...,...,...,...,...,...
X5,2025,12,RestOfWorld,9281,68198,632945638,0.201,5.89,2.37,1.41
X7,2025,12,RestOfWorld,12785,91839,1174161615,0.203,5.89,2.37,1.41
i4,2025,12,RestOfWorld,4906,63437,311221922,0.180,5.89,2.37,1.41
iX,2025,12,RestOfWorld,7871,73867,581407157,0.196,5.89,2.37,1.41
MINI,2025,12,RestOfWorld,6732,41811,281471652,0.167,5.89,2.37,1.41

In [63]:
#Looping 

for i in bmw.index:
    print(i)

3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI
3 Series
5 Series
X3
X5
X7
i4
iX
MINI

In [ ]:
#operators
100 - marks_series #an example of broadcasting

maths      11
science    22
hindi      54
English    21
Name: Yash ke marks, dtype: int64

In [ ]:
#Relationals operator

marks_series >= 50

maths       True
science     True
hindi      False
English     True
Name: Yash ke marks, dtype: bool

In [ ]:
#Boolean indexing on series

marks_series[marks_series > 50] #how many student score greater tha 50 in the test

maths      89
science    78
English    79
Name: Yash ke marks, dtype: int64

In [74]:
#find the number of ducks

marks_series[marks_series == 0].size

0

In [ ]:
#Count the number of frequency
marks_series[marks_series > 60].size

3

In [80]:
num_bmw = code.value_counts()
num_bmw

Coding_Hours  Coffee_Cups  Bugs_Fixed
1             1            6             123
9             5            45            119
                           46            118
6             3            29            115
3             2            16            113
                                        ...
6             7            32              1
2             4            10              1
6             0            22              1
12            7            72              1
3             4            28              1
Name: count, Length: 1169, dtype: int64

In [81]:
#Ploting Graphs on series
bmw.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [87]:
subs = pd.read_csv("/Users/yashnandankar/StaTic_NeuraL/AI_Learn/subs.csv")

In [88]:
subs.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.