In [2]:
import pandas as pd
import numpy as np
import matplotlib as plot

In [3]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
pd.Series([1,2,3,4,5,6,7,8],index=index_val)

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [4]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [5]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels[1]

# 2. pd.MultiIndex.from_product()
multiindex = pd.MultiIndex.from_product([['cse','ecs'],[2019,2020,2021,2022]])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ecs', 2019),
            ('ecs', 2020),
            ('ecs', 2021),
            ('ecs', 2022)],
           )

In [6]:
#creatin a series using multiindex
a = pd.Series([1,2,3,4,5,6,7,8],multiindex)
a['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [7]:
#unstack
temp = a.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ecs     5     6     7     8

In [8]:
#stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ecs  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [9]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ecs 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [10]:
branch_df2 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16]
    ],
    index=multiindex,
    columns=['avg_package','student']

)

branch_df2

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ecs 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [11]:
branch_df1['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ecs  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [12]:
actual = np.random.randint(1,100,16).reshape(4,4)
actual

array([[75, 97, 61, 64],
       [61, 28, 78, 99],
       [79, 40, 23, 55],
       [91, 33, 40, 71]])

In [13]:
#Multiindex df from columns perspective 

branch_df2 = pd.DataFrame(actual,index=[2019,2020,2021,2022],
                          columns=pd.MultiIndex.from_product([['Delhi','Mumbai'],['Avg_package','student']]))
branch_df2

           Delhi              Mumbai
     Avg_package student Avg_package student
2019          75      97          61      64
2020          61      28          78      99
2021          79      40          23      55
2022          91      33          40      71

In [14]:
branch_df2['Delhi']['Avg_package']

2019    75
2020    61
2021    79
2022    91
Name: Avg_package, dtype: int64

In [15]:
branch_df2.loc[2019]

Delhi   Avg_package    75
        student        97
Mumbai  Avg_package    61
        student        64
Name: 2019, dtype: int64

In [16]:
#Stacking and Unstacking 
#Row -> Column  this helps to reshape the data. 
branch_df1.unstack().unstack()

avg_package  2019  cse     1
                   ecs     9
             2020  cse     3
                   ecs    11
             2021  cse     5
                   ecs    13
             2022  cse     7
                   ecs    15
students     2019  cse     2
                   ecs    10
             2020  cse     4
                   ecs    12
             2021  cse     6
                   ecs    14
             2022  cse     8
                   ecs    16
dtype: int64

In [17]:
branch_df1.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ecs           9   11   13   15       10   12   14   16

In [18]:
branch_df1.stack()

cse  2019  avg_package     1
           students        2
     2020  avg_package     3
           students        4
     2021  avg_package     5
           students        6
     2022  avg_package     7
           students        8
ecs  2019  avg_package     9
           students       10
     2020  avg_package    11
           students       12
     2021  avg_package    13
           students       14
     2022  avg_package    15
           students       16
dtype: int64

In [20]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ecs 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [21]:
#Multi index Dataframe

#head and tail
branch_df2

           Delhi              Mumbai
     Avg_package student Avg_package student
2019          75      97          61      64
2020          61      28          78      99
2021          79      40          23      55
2022          91      33          40      71

In [22]:
branch_df3.head(3)

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0

In [24]:
branch_df3.shape

(8, 4)

In [30]:
branch_df3.info()
branch_df3.duplicated()
branch_df3.isnull()

<class 'pandas.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ecs', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 639.0 bytes

               delhi               mumbai
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ecs 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [33]:
#Extracting a single row 

branch_df3.loc[('cse',2022)]
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ecs 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [35]:
#multiple row

branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0

In [38]:
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ecs 2019           9       10           0        0

In [40]:
branch_df3['delhi']['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ecs  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [42]:
branch_df3.iloc[:,1:3]

            delhi      mumbai
         students avg_package
cse 2019        2           0
    2020        4           0
    2021        6           0
    2022        8           0
ecs 2019       10           0
    2020       12           0
    2021       14           0
    2022       16           0

In [44]:
#Extracting both 
branch_df3.iloc[[0,4],[1,2]]

            delhi      mumbai
         students avg_package
cse 2019        2           0
ecs 2019       10           0

In [46]:
#Sorting index
#both -> decending ->diff order
branch_df3.sort_index(ascending=False)

               delhi               mumbai
         avg_package students avg_package students
ecs 2022          15       16           0        0
    2021          13       14           0        0
    2020          11       12           0        0
    2019           9       10           0        0
cse 2022           7        8           0        0
    2021           5        6           0        0
    2020           3        4           0        0
    2019           1        2           0        0

In [47]:
branch_df3.sort_index(ascending=[False,True])

               delhi               mumbai
         avg_package students avg_package students
ecs 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0