In [1]:
import pandas as pd
import numpy as np
import matplotlib as plot

In [2]:
# can we have multiple index? Let's try
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
pd.Series([1,2,3,4,5,6,7,8],index=index_val)

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [3]:
# The solution -> multiindex series(also known as Hierarchical Indexing)
# multiple index levels within a single index

In [4]:
# how to create multiindex object
# 1. pd.MultiIndex.from_tuples()
index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels[1]

# 2. pd.MultiIndex.from_product()
multiindex = pd.MultiIndex.from_product([['cse','ecs'],[2019,2020,2021,2022]])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ecs', 2019),
            ('ecs', 2020),
            ('ecs', 2021),
            ('ecs', 2022)],
           )

In [5]:
#creatin a series using multiindex
a = pd.Series([1,2,3,4,5,6,7,8],multiindex)
a['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [6]:
#unstack
temp = a.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ecs     5     6     7     8

In [7]:
#stack
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ecs  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [8]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ecs 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [9]:
branch_df2 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16]
    ],
    index=multiindex,
    columns=['avg_package','student']

)

branch_df2

          avg_package  student
cse 2019            1        2
    2020            3        4
    2021            5        6
    2022            7        8
ecs 2019            9       10
    2020           11       12
    2021           13       14
    2022           15       16

In [10]:
branch_df1['students']

cse  2019     2
     2020     4
     2021     6
     2022     8
ecs  2019    10
     2020    12
     2021    14
     2022    16
Name: students, dtype: int64

In [23]:
actual = np.random.randint(1,100,16).reshape(4,4)
actual

array([[55, 73, 77, 75],
       [92, 70, 60, 85],
       [50, 28,  6, 35],
       [13, 81, 46, 21]])

In [25]:
#Multiindex df from columns perspective 

branch_df2 = pd.DataFrame(actual,index=[2019,2020,2021,2022],
                          columns=pd.MultiIndex.from_product([['Delhi','Mumbai'],['Avg_package','student']]))
branch_df2

           Delhi              Mumbai
     Avg_package student Avg_package student
2019          55      73          77      75
2020          92      70          60      85
2021          50      28           6      35
2022          13      81          46      21

In [ ]:
branch_df2['Delhi']['Avg_package']

2019    55
2020    92
2021    50
2022    13
Name: Avg_package, dtype: int64

In [32]:
branch_df2.loc[2019]

Delhi   Avg_package    55
        student        73
Mumbai  Avg_package    77
        student        75
Name: 2019, dtype: int64

In [ ]:
#Stacking and Unstacking 
#Row -> Column 
branch_df1.unstack()

    avg_package                students
           2019 2020 2021 2022     2019 2020 2021 2022
cse           1    3    5    7        2    4    6    8
ecs           9   11   13   15       10   12   14   16